
import { Talent } from './types';

// Using high-quality Unsplash images to simulate the look and feel of the fitness/lifestyle roster
export const ROSTER_DATA: Talent[] = [
  {
    id: '1',
    name: 'Fennah Jones',
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=800',
    tags: ['Fitness', 'Lifestyle', 'Holistic', 'Food', 'Recipe'],
    location: 'United Kingdom',
    address: '45 Kensington High St, London W8 5ED, UK',
    gender: 'Female',
    audienceAge: '18-24',
    stats: [
      { platform: 'Instagram', followerCount: '57,400', link: '#' },
      { platform: 'TikTok', followerCount: '29,500', link: '#' },
      { platform: 'YouTube', followerCount: '8,140', link: '#' },
    ],
    bio: "Fennah brings a raw and authentic approach to fitness, blending high-performance training with everyday lifestyle content. Her community trusts her for realistic advice and consistent motivation.",
    engagementRate: "4.8%",
    avgViews: "45K",
    totalReach: "95K",
    brands: ['Gymshark', 'NOCCO', 'Real Good Foods'],
    demographics: { male: 35, female: 65, topCountries: ['UK', 'USA', 'Australia'] }
  },
  {
    id: '2',
    name: 'Joe Shulk',
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&q=80&w=800',
    tags: ['Fitness', 'Bodybuilder', 'Comedy'],
    location: 'United States',
    address: '1234 Sunset Blvd, Los Angeles, CA 90028, USA',
    gender: 'Male',
    audienceAge: '18-24',
    stats: [
      { platform: 'Instagram', followerCount: '386,000', link: '#' },
      { platform: 'TikTok', followerCount: '2,400,000', link: '#' },
      { platform: 'YouTube', followerCount: '304,000', link: '#' },
    ],
    bio: "Known for his explosive energy and bodybuilding expertise, Joe has cultivated one of the most engaged male fitness communities on TikTok. He specializes in supplement integration and workout challenges.",
    engagementRate: "7.2%",
    avgViews: "1.2M",
    totalReach: "3.1M",
    brands: ['C4', 'Gymshark', 'Manscaped'],
    demographics: { male: 85, female: 15, topCountries: ['USA', 'Canada', 'UK'] }
  },
  {
    id: '3',
    name: 'Sophie Rose',
    image: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&q=80&w=800',
    tags: ['Athlete', 'Professional', 'Travel', 'Fitness'],
    location: 'United Kingdom',
    address: '78 Oxford Street, Manchester M1 5NH, UK',
    gender: 'Female',
    audienceAge: '25-34',
    stats: [
      { platform: 'Instagram', followerCount: '146,000', link: '#' },
      { platform: 'TikTok', followerCount: '177,100', link: '#' },
      { platform: 'YouTube', followerCount: '52,600', link: '#' },
    ],
    bio: "Sophie is a professional hybrid athlete who inspires women to lift heavy and run fast. Her content focuses on performance, nutrition, and the mental aspect of training.",
    engagementRate: "5.5%",
    avgViews: "85K",
    totalReach: "375K",
    brands: ['NOCCO', 'Gymshark'],
    demographics: { male: 40, female: 60, topCountries: ['UK', 'Ireland', 'USA'] }
  },
  {
    id: '4',
    name: 'Tren Twins',
    image: 'https://images.unsplash.com/photo-1549476464-37392f717541?q=80&w=800&auto=format&fit=crop',
    tags: ['Fitness', 'Bodybuilder', 'Comedy'],
    location: 'United States',
    address: '567 5th Avenue, New York, NY 10017, USA',
    gender: 'Male',
    audienceAge: '18-24',
    stats: [
      { platform: 'Instagram', followerCount: '2,100,000', link: '#' },
      { platform: 'TikTok', followerCount: '2,399,999', link: '#' },
      { platform: 'YouTube', followerCount: '1,900,000', link: '#' },
    ],
    bio: "The Tren Twins have taken the internet by storm with their intense personality and heavy lifting content. They command massive attention and drive immediate sales for partner brands.",
    engagementRate: "9.8%",
    avgViews: "2.5M",
    totalReach: "6.4M",
    brands: ['Bucked Up', 'Gymshark', 'C4'],
    demographics: { male: 92, female: 8, topCountries: ['USA', 'UK', 'Australia'] }
  },
  {
    id: '5',
    name: 'Aaliyah',
    image: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&q=80&w=800',
    tags: ['Fitness', 'Fashion', 'Beauty', 'Lifestyle'],
    location: 'United States',
    gender: 'Female',
    audienceAge: '25-34',
    stats: [
      { platform: 'Instagram', followerCount: '64,400', link: '#' },
      { platform: 'TikTok', followerCount: '18,800', link: '#' },
    ],
    bio: "Aaliyah seamlessly blends fitness with high-end fashion, appealing to a sophisticated audience that values aesthetics and wellness. Her content is highly polished and aspirational.",
    engagementRate: "3.9%",
    avgViews: "22K",
    totalReach: "83K",
    brands: ['Element', 'Real Good Foods'],
    demographics: { male: 20, female: 80, topCountries: ['USA', 'Canada'] }
  },
  {
    id: '6',
    name: 'Aayrn Rozier',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800',
    tags: ['Fitness', 'Athlete', 'Professional'],
    location: 'United States',
    gender: 'Male',
    audienceAge: '18-24',
    stats: [
      { platform: 'Instagram', followerCount: '49,250', link: '#' },
      { platform: 'TikTok', followerCount: '12,500', link: '#' },
      { platform: 'YouTube', followerCount: '175', link: '#' },
      { platform: 'Facebook', followerCount: '2,600', link: '#' },
    ],
    bio: "A rising star in the calisthenics scene, Aayrn demonstrates incredible body control and strength. His tutorial-style content has high save and share rates.",
    engagementRate: "6.1%",
    avgViews: "15K",
    totalReach: "65K",
    brands: ['Gymshark', 'Element'],
    demographics: { male: 70, female: 30, topCountries: ['USA', 'Germany'] }
  },
  {
    id: '7',
    name: 'Abe Kikirov',
    image: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&q=80&w=800',
    tags: ['Fitness', 'Bodybuilder', 'Professional'],
    location: 'United States',
    gender: 'Male',
    audienceAge: '25-34',
    stats: [
      { platform: 'Instagram', followerCount: '122,000', link: '#' },
      { platform: 'TikTok', followerCount: '331,600', link: '#' },
      { platform: 'YouTube', followerCount: '190,000', link: '#' },
    ],
    bio: "Abe focuses on science-based hypertrophy training. His detailed breakdowns of exercises attract a dedicated audience looking to optimize their training.",
    engagementRate: "5.0%",
    avgViews: "150K",
    totalReach: "643K",
    brands: ['C4', 'Bucked Up'],
    demographics: { male: 80, female: 20, topCountries: ['USA', 'Canada', 'UK'] }
  },
  {
    id: '8',
    name: 'Adam Bank',
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&q=80&w=800',
    tags: ['Athlete', 'Fitness', 'Comedy', 'Lifestyle'],
    location: 'United States',
    gender: 'Male',
    audienceAge: '18-24',
    stats: [
      { platform: 'Instagram', followerCount: '525,000', link: '#' },
      { platform: 'TikTok', followerCount: '1,300,000', link: '#' },
    ],
    bio: "Adam brings a high-energy, vlog-style approach to his fitness journey. He connects deeply with his audience through storytelling and daily life updates.",
    engagementRate: "6.5%",
    avgViews: "500K",
    totalReach: "1.8M",
    brands: ['Gymshark', 'Manscaped', 'NOCCO'],
    demographics: { male: 60, female: 40, topCountries: ['USA'] }
  },
  {
    id: '9',
    name: 'Adam J Ellison',
    image: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?auto=format&fit=crop&q=80&w=800',
    tags: ['Fitness', 'Professional', 'Food'],
    location: 'United Kingdom',
    gender: 'Male',
    audienceAge: '25-34',
    stats: [
      { platform: 'Instagram', followerCount: '831,000', link: '#' },
      { platform: 'YouTube', followerCount: '34,400', link: '#' },
      { platform: 'Facebook', followerCount: '466,000', link: '#' },
    ],
    bio: "Adam is a veteran in the fitness industry, known for his no-nonsense approach to fat loss and muscle building. His older demographic has high purchasing power.",
    engagementRate: "4.2%",
    avgViews: "100K",
    totalReach: "1.3M",
    brands: ['Real Good Foods', 'Element'],
    demographics: { male: 55, female: 45, topCountries: ['UK', 'USA'] }
  },
  {
    id: '10',
    name: 'Adam The Dunker',
    image: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&q=80&w=800',
    tags: ['Lifestyle', 'Fitness', 'Athlete', 'Gaming'],
    location: 'United States',
    gender: 'Male',
    audienceAge: '13-17',
    stats: [
      { platform: 'Instagram', followerCount: '424,000', link: '#' },
      { platform: 'TikTok', followerCount: '1,400,000', link: '#' },
      { platform: 'YouTube', followerCount: '1,530,000', link: '#' },
    ],
    bio: "Specializing in vertical jump training and basketball lifestyle, Adam captures the attention of young athletes worldwide.",
    engagementRate: "8.5%",
    avgViews: "800K",
    totalReach: "3.3M",
    brands: ['NOCCO', 'C4'],
    demographics: { male: 90, female: 10, topCountries: ['USA', 'Philippines'] }
  },
  {
    id: '11',
    name: 'Ahmed Fadl',
    image: 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&q=80&w=800',
    tags: ['Gaming', 'Comedy', 'Lifestyle'],
    location: 'United States',
    gender: 'Male',
    audienceAge: '18-24',
    stats: [
      { platform: 'Instagram', followerCount: '51,900', link: '#' },
      { platform: 'Facebook', followerCount: '213,000', link: '#' },
    ],
    bio: "Ahmed bridges the gap between gaming and lifestyle, creating entertaining content that keeps his audience hooked for long durations.",
    engagementRate: "3.5%",
    avgViews: "30K",
    totalReach: "265K",
    brands: ['Element'],
    demographics: { male: 75, female: 25, topCountries: ['USA', 'Egypt'] }
  },
  {
    id: '12',
    name: 'Aidan Smith',
    image: 'https://images.unsplash.com/photo-1483721310020-03333e577078?q=80&w=800&auto=format&fit=crop',
    tags: ['Fitness', 'Fashion', 'Beauty'],
    location: 'United Kingdom',
    gender: 'Male',
    audienceAge: '18-24',
    stats: [
      { platform: 'Instagram', followerCount: '74,400', link: '#' },
      { platform: 'TikTok', followerCount: '137,500', link: '#' },
      { platform: 'YouTube', followerCount: '2,084', link: '#' },
    ],
    bio: "Aidan's aesthetic physique and cinematic editing style make his content stand out. He appeals to those looking for artistic inspiration in their fitness journey.",
    engagementRate: "7.0%",
    avgViews: "60K",
    totalReach: "214K",
    brands: ['Gymshark', 'Bucked Up'],
    demographics: { male: 85, female: 15, topCountries: ['UK', 'Germany'] }
  },
];
